import { sample } from 'lodash-es';

export default function laotians() {
  let names;
  const type = Math.random() > 0.5 ? 0 : 1;
  const nm1 = ['Akamu', 'Analu', 'Aulii', 'Bane', 'Bane ', 'Havika', 'Ikaika', 'Kahoku', 'Kai', 'Kaili', 'Kaipo', 'Kalani', 'Kale', 'Kale ', 'Kalei', 'Kanoa', 'Kapono', 'Kawaii', 'Keahi', 'Keanu', 'Kelii', 'Keoki', 'Keola', 'Keon', 'Keona', 'Keowynn', 'Kimo', 'Kimo ', 'Koa', 'Konala', 'Kye', 'Kye ', 'Lae', 'Lani', 'Leilani', 'Liko', 'Lilo', 'Loe', 'Maiele', 'Maik', 'Makaio', 'Makan', 'Makan ', 'Makani', 'Malo', 'Malo ', 'Mauli', 'Meka', 'Mele', 'Moana', 'Moke', 'Mya', 'Noi', 'Oke', 'Palani', 'Paxathipatai', 'Pekelo', 'Phetdum', 'Phonesavanh', 'Saravan', 'Sathanalat', 'Sengprachanh', 'Sommai', 'Somphone', 'Songkram', 'Sonxai', 'Teyvada', 'Ulani', 'Wongduan', 'Xaisomboun'];
  const nm2 = ['Aelan', 'Ailani', 'Akela', 'Alaina', 'Alamea', 'Alana', 'Alani', 'Alanna', 'Alaula', 'Aleka', 'Alika', 'Alli', 'Allyn', 'Aloha', 'Alohi', 'Alohilani', 'Alona', 'Alun', 'Alyn', 'Anani', 'Ani', 'Aolani', 'Aolha', 'Aulani', 'Aulii', 'Bane', 'Bounmy', 'Chansouda', 'Chanthadeth', 'Dorit', 'Edena', 'Gladi', 'Haimi', 'Haleah', 'Haleigha', 'Halia', 'Hina', 'Inoke', 'Iokina', 'Iolana', 'Iolani', 'Ipo', 'Iwalani', 'Jeanitha', 'Kai', 'Kaiah', 'Kailani', 'Kailea', 'Kaili', 'Kalaina', 'Kalama', 'Kalani', 'Kalea', 'Kaleah', 'Kalei', 'Kaleigh', 'Kaleikaumaka', 'Kalena', 'Kalia', 'Kalina', 'Kaloni', 'Kamea', 'Kawailani', 'Kawena', 'Keahi', 'Keala', 'Keanu', 'Keiki', 'Keilana', 'Keili', 'Kekiokolanee', 'Kekona', 'Keola', 'Ketsada', 'Khampheng', 'Kiana', 'Kiele', 'Kieli', 'Kina', 'Kinipela', 'Konane', 'Lae', 'Lahela', 'Laina', 'Lanai', 'Lani', 'Lanikai', 'Laya', 'Leigha', 'Leilana', 'Leilana ', 'Leilani', 'Leilanie', 'Liliha', 'Lilo', 'Loe', 'Lokelani', 'Lulani', 'Mahina', 'Maik', 'Maile', 'Makaio', 'Makala', 'Makana', 'Makani', 'Makelina', 'Makenna', 'Malana', 'Maleah', 'Malia', 'Malu', 'Mauli', 'Mei', 'Milani', 'Mily', 'Moana', 'Moanna', 'Moke', 'Mya', 'Nalani', 'Nalanie', 'Nani', 'Napua', 'Noelani', 'Noma', 'Okalani', 'Oke', 'Okelani', 'Okilani', 'Oliana', 'Olina', 'Onaona', 'Palila', 'Peni', 'Phetmany', 'Phetsavanh', 'Pilialoha', 'Pilis', 'Pualani', 'Roselani', 'Saengvone', 'Sasilvia', 'Sathit', 'Somphone', 'Soukchanda', 'Sousida', 'Suke', 'Ulani', 'Ululani', 'Wanika'];
  const nm3 = ['Bokeo', 'Bouphavanh', 'Bouvanaat', 'Champasack', 'Champasak', 'Chanthanane', 'Chanthavong', 'Chanthavong', 'Chanthraphone', 'Cheruene', 'Douangmala', 'Douangvily', 'Genevong', 'Inthisane', 'Kaewdara', 'Keobounphanh', 'Keobunta', 'Keomany', 'Keopraseuth', 'Keothavong', 'Kethavongsa', 'Ketthavong', 'Khamchanh', 'Khamsomphou', 'Khamvongsouk', 'Khanthavong', 'Khotpanya', 'Khouphongsy', 'Kittiphan', 'Kommandam', 'Kouanchao', 'Lengsavad', 'Louangrath', 'Malaythong', 'Manwilaivong', 'Menorath', 'Ornpaeng', 'Oudomphonh', 'Pakdimounivong', 'Phanivong', 'Phankham', 'Phaophanit', 'Phengsavath', 'Phetphommasouk', 'Phommajack', 'Phommasane', 'Phommathep', 'Phomsouvanh', 'Phomvihane', 'Phothisarath', 'Phoumsavanh', 'Phoutthasinh', 'Phrasavath', 'Rattanavongsa', 'Saenbouthalath', 'Saengsavang', 'Saengsouriya', 'Saenthavisouk', 'Savang', 'Sayasone', 'Sayavong', 'Saysamongdy', 'Saysanasy', 'Seeha', 'Sengprachanh', 'Sengtavisouk', 'Siharath ', 'Simnouansai', 'Siphandon', 'Sisoulith', 'Siyavong', 'Somphonpadee', 'Somphousiharath', 'Sonexarth', 'Souksanh', 'Soulignavong', 'Southavilay', 'Souvannaphouma', 'Syrypanha', 'Syvongsa', 'Tayvihane', 'Thammasith', 'Thammavong', 'Thammavong ', 'Thammavongsa', 'Thepsenavong', 'Thiamphasone', 'Thonemany', 'Vatthana', 'Viravongs', 'Vongphachanh', 'Vongphakdy', 'Vongsamphanh', 'Vongsay', 'Vongvichit', 'Vongvilay', 'Vorachith', 'Xiengboree'];
  {
    if (type === 1) {
      names = `${sample(nm2)} ${sample(nm3)}`;
    } else {
      names = `${sample(nm1)} ${sample(nm3)}`;
    }
    return names;
  }
}
