import sample from 'lodash/sample';

export default function heists() {
  let names;
  const nm2 = ['Heist', 'Sting', 'Robbery', 'Heist', 'Robbery', 'Heist'];
  const nm1 = ['10,000 Mile', 'Acrobatics', 'Aerial', 'Alpha', 'Anarchy', 'Angel', 'Animal', 'Annihilation', 'Apex', 'Aquatic', 'Assassination', 'Asset', 'Avian', 'Backfire', 'Baited', 'Balance', 'Bankrupt', 'Basket Case', 'Benign', 'Black Diamond', 'Blind', 'Blood Diamond', 'Bloody', 'Blunder', 'Bogus', 'Bread', 'Breadcrumb', 'Breakdown', 'Bribery', 'Bulldozer', 'Bully', 'Business', 'Butcher', 'CEO', 'Cannibal', 'Champion', 'Chaos', 'Charade', 'Child\'s Play', 'Cipher', 'Civil', 'Clown', 'Clumsy', 'Copycat', 'Corpse', 'Corruption', 'Counterfeit', 'Crooked', 'Decimation', 'Demolition', 'Demon', 'Desperation', 'Dilemma', 'Diplomat', 'Dirty', 'Disaster', 'Diversion', 'Divine', 'Dread', 'Duped', 'Duplicate', 'Earthquake', 'Echo', 'Enigma', 'Epitome', 'Equality', 'Escort', 'Ethereal', 'Evanescence', 'Evaporation', 'Evil Incarnate', 'Extermination', 'Fake Out', 'False', 'Family', 'Feral', 'Fire', 'Floating', 'Flood', 'Fluke', 'Flying', 'Fool\'s', 'Fool\'s Errand', 'Foolproof', 'Forsaken', 'Framed', 'Fruitcake', 'Fury', 'Gambit', 'Genocide', 'Getaway', 'Ghost', 'Gopher', 'Grave', 'Grease', 'Great Food', 'Grim', 'Grim Reaper', 'Guardian', 'Gunpowder', 'Hallowed', 'Happy', 'Harrier', 'Hollow', 'Homicide', 'Honeycomb', 'Honorable', 'Hostage', 'Hummiliation', 'Hurricane', 'Hysteria', 'Ignition', 'Illusion', 'Imaginary', 'Inferno', 'Insanity', 'Insider', 'Intimidation', 'Investment', 'Ire', 'Junior', 'Killing', 'Labyrinth', 'Landmine', 'Laughing', 'Lethal', 'Lightning', 'Limbo', 'Liquid', 'Lookalike', 'Lottery', 'Lucky', 'Lunatic', 'Mad', 'Magician', 'Maniac', 'Martyr', 'Masked', 'Massacre', 'Medieval', 'Meteor', 'Midnight', 'Mile High', 'Mime', 'Mirror', 'Misdirection', 'Mobile', 'Mock', 'Mole', 'Mulligan', 'Mystery', 'Naked', 'Neglect', 'Neighbor', 'Noble', 'Noon', 'Obliteration', 'Oblivion', 'Omega', 'Paragon', 'Parallel', 'Pawn', 'Perfect', 'Phantom Thief', 'Picnic', 'Plague', 'Poison', 'Polite', 'Premium', 'Prime', 'Prototype', 'Pseudo', 'Psycho', 'Punishment', 'Rampage', 'Red Herring', 'Refund', 'Repeat', 'Replica', 'Reverse', 'Riddle', 'Robin Hood', 'Rookie', 'Ruthless', 'Sacrificial', 'Savage', 'Scapegoat', 'Seduction', 'Senior', 'Sentinel', 'Shepherd', 'Shock and Awe', 'Slayer', 'Sleaze', 'Smoke Screen', 'Smoke and Mirrors', 'Smooth', 'Smut', 'Stained', 'Sugarcoated', 'Sullied', 'Switcheroo', 'Termination', 'Terror', 'Textbook', 'Thunder', 'Titan', 'Torture', 'Treasure', 'Twin', 'Tyrant', 'Undead', 'Underdog', 'Vanishing', 'Venom', 'Vigilante', 'Void', 'Voodoo', 'Walking Dead', 'Warden', 'Watchdog', 'Wild Goose', 'Witchcraft', 'Worthless', 'Zero', 'Zombie'];
  {
    names = `The ${sample(nm1)} ${sample(nm2)}`;
    return names;
  }
}
